image: registry.fedoraproject.org/fedora:latest


variables:
  CURRENT_VERSION: "$(mvn validate | grep Build | awk '{print $4}')"



stages:
  - test
  - build
  - create-container-image
  
test-java-project:
  stage: test
  script:
    mvn test
  artifacts:
    paths:
      - /home/gitlab-runner/

build-java-project:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - "**/target"

container-image:
  stage: create-container-image
  script:
     - buildah --userns=keep-id bud --annotation-file metadata.txt -t ankh/netcompass:latest .
  tags:
     - buildah

  