image: registry.fedoraproject.org/fedora:latest

stages:
  - test
  - build
test-java-project:
  stage: test
  script:
    mvn test
  artifacts:
    paths:
      - /home/gitlab-runner/

build-java-project:
  stage: build
  script:
    - mvn package
    - buildah --userns=keep-id bud -t ankh/netcompass:latest .
  tags:
    - buildah
  artifacts:
    paths:
      - "**/target"
