image: registry.fedoraproject.org/fedora:latest


variables:
  CURRENT_VERSION: "$(mvn validate | grep Build | awk '{print $4}')"



stages:
  - test
  - build
  - create-container-image
  
test-java-project:
  stage: test
  script:
    mvn test
  artifacts:
    paths:
      - /home/gitlab-runner/

build-java-project:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - "**/target"

container-image:
  stage: create-container-image
  script:
     - buildah --userns=keep-id bud --annotation "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --annotation "org.opencontainers.image.authors=Lucas Nishimura <lucas.nishimura at telefonica.com>" --annotation "org.opencontainers.image.title=Netcompass API" --annotation "org.opencontainers.image.description=Microserviço do Netcompass Backend Java Spring" --annotation "org.opencontainers.image.version=$CURRENT_DATE" -t ankh/netcompass:latest .
  tags:
     - buildah

  