apiVersion: v1
kind: Pod
metadata:
  name: inventory-manager-db
spec:
  volumes:
    - name: pvc-8f28fb08-b301-4fe2-b21c-0c0b31d21447
      persistentVolumeClaim:
        claimName: netcompass-db-volume-claim
  containers:
    - name: inventory-manager-db
      image: quay.apps.mgmt.telcostack.br.telefonica.com/netcompass/netcompass-server/arangodb:latest
      resources:
        requests:
          memory: "16384Mi"
          cpu: "24"
        limits:
          memory: "32768Mi"
          cpu: "32"
      ports:
        - name: arango-port
          containerPort: 8529
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/lib/arangodb3"
          name: pvc-8f28fb08-b301-4fe2-b21c-0c0b31d21447
      env:
        - name: ARANGO_ROOT_PASSWORD
          value: prod@inventory15
