apiVersion: v1
kind: Pod
metadata:
  name: inventory-manager-api
spec:
  volumes:
    - name: pvc-8e757e50-ce35-4315-8265-fe14095065ca
      persistentVolumeClaim:
        claimName: netcompass-app-volume-claim
  containers:
    - name: inventory-manager-api
      image: quay.apps.mgmt.telcostack.br.telefonica.com/netcompass/netcompass-server/osstelecom-jdk11:0.3
      resources:
        requests:
          memory: "5120Mi"
          cpu: "4"
        limits:
          memory: "5120Mi"
          cpu: "8"
      ports:
        - name: api-https
          containerPort: 9000
          protocol: TCP
      volumeMounts:
        - mountPath: "/app/inventory-manager"
          name: pvc-8e757e50-ce35-4315-8265-fe14095065ca
      env:
        - name: JAR_PATH
          value: /app/inventory-manager
        - name: JAR_ARGS
          value: -Xmx4G
        - name: JAR_NAME
          value: inventory-manager-1.0.0-alpha-security.jar
