apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcompass-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcompass-api-deployment
  template:
    metadata:
      labels:
        app: netcompass-api-deployment
    spec:
      containers:
      - name: netcompass-api
        image: quay.apps.mgmt.telcostack.br.telefonica.com/netcompass/netcompass-server/osstelecom-jdk11:latest
        securityContext:
          runAsUser: 1001280000
        resources:
          requests:
            memory: "5120Mi"
            cpu: "4"
          limits:
            memory: "5120Mi"
            cpu: "8"
        ports:
          - name: api-https
            containerPort: 9000
            protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /app/inventory-manager/config/
        volumeDevices:
          - devicePath: "/dev/xvda"
            name: netcompass-volume-pvc
        env:
          - name: JAR_PATH
            value: /app/inventory-manager
          - name: JAR_ARGS
            value: -Xmx4G
          - name: JAR_NAME
            value: inventory-manager-1.0.0-alpha-security.jar
      volumes:
        - name: netcompass-volume-pvc
          persistentVolumeClaim:
            claimName: netcompass-app-volume-claim
        - name: config-volume
          configMap:
            name: inventory-config
