apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcompass-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcompass-api-deployment
  template:
    metadata:
      labels:
        app: netcompass-api-deployment
    spec:
      containers:
      - name: inventory-manager-api
        metadata:
          labels:
            app: netcompass-api
        image: quay.apps.mgmt.telcostack.br.telefonica.com/netcompass/netcompass-server/netcompass-api
        resources:
          requests:
            memory: "5120Mi"
            cpu: "4"
          limits:
            memory: "5120Mi"
            cpu: "8"
        ports:
          - name: api-https
            containerPort: 9000
            protocol: TCP
        volumeMounts:
          # - mountPath: "/app/inventory-manager"
          #   name: netcompass-app-volume
          - name: config-volume
            mountPath: /app/inventory-manager/config/
        volumeDevices:
          - name: netcompass-app-volume
            devicePath: /dev/xvda 
        env:
          - name: JAR_PATH
            value: /app/inventory-manager
          - name: JAR_ARGS
            value: -Xmx4G -Dspring.profiles.active=mvp
          - name: JAR_NAME
            value: inventory-manager-1.0.0-alpha.jar
          - name: SPRING_PROFILES_DEFAULT
            value: mvp
      volumes:
        - name: netcompass-app-volume
          persistentVolumeClaim:
            claimName: netcompass-app-volume-claim
          mountOptions:
            - rw
            - nouuid
            - noatime
          subPath: myapp-data
        - name: config-volume
          configMap:
            name: inventory-config
