apiVersion: v1
kind: Pod
metadata:
  name: inventory-manager-api
spec:
  volumes:
    - name: netcompass-app-volume
      persistentVolumeClaim:
        claimName: netcompass-app-volume-claim
    - name: config-volume
      configMap:
        name: inventory-config
  containers:
    - name: inventory-manager-api
      image: quay.apps.mgmt.telcostack.br.telefonica.com/netcompass/netcompass-server/osstelecom-jdk11
      resources:
        requests:
          memory: "5120Mi"
          cpu: "4"
        limits:
          memory: "5120Mi"
          cpu: "8"
      ports:
        - name: api-https
          containerPort: 9000
          protocol: TCP
      volumeMounts:
        - mountPath: "/app/inventory-manager"
          name: netcompass-app-volume
        - name: config-volume
          mountPath: /app/inventory-manager/config/
      env:
        - name: JAR_PATH
          value: /app/inventory-manager
        - name: JAR_ARGS
          value: -Xmx4G
        - name: JAR_NAME
          value: inventory-manager-1.0.0-alpha-security.jar
