
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/*
 * Copyright (C) 2023 Lucas Nishimura <lucas.nishimura@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
/**
 *
 * @author Lucas Nishimura <lucas.nishimura@gmail.com>
 * @created 28.06.2023
 */
public class JsonFilterTest {

    public static void main(String[] args) {

        String yourJsonString = "{\n"
                + "  \"statusCode\": 0,\n"
                + "  \"payLoad\": {\n"
                + "    \"domain\": {\n"
                + "      \"domainName\": \"network\",\n"
                + "      \"connections\": \"network_connections\",\n"
                + "      \"nodes\": \"network_nodes\",\n"
                + "      \"serviceConnections\": \"string\",\n"
                + "      \"services\": \"network_services\",\n"
                + "      \"connectionLayer\": \"string\",\n"
                + "      \"serviceLayer\": \"string\",\n"
                + "      \"circuits\": \"string\",\n"
                + "      \"circuitsLayer\": \"string\",\n"
                + "      \"domainDescription\": \"string\",\n"
                + "      \"metrics\": \"string\",\n"
                + "      \"resourceCount\": 0,\n"
                + "      \"connectionCount\": 0,\n"
                + "      \"circuitCount\": 0,\n"
                + "      \"serviceCount\": 0,\n"
                + "      \"atomicId\": 0,\n"
                + "      \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "      \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "    },\n"
                + "    \"domainName\": \"network\",\n"
                + "    \"installationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "    \"activationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "    \"inactivationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "    \"lastModifiedDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "    \"insertedDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "    \"deleted\": true,\n"
                + "    \"readOnly\": true,\n"
                + "    \"isLeaf\": true,\n"
                + "    \"isConsumable\": true,\n"
                + "    \"isConsumer\": true,\n"
                + "    \"consumableMetric\": {\n"
                + "      \"id\": \"string\",\n"
                + "      \"key\": \"string\",\n"
                + "      \"domain\": {\n"
                + "        \"domainName\": \"network\",\n"
                + "        \"connections\": \"network_connections\",\n"
                + "        \"nodes\": \"network_nodes\",\n"
                + "        \"serviceConnections\": \"string\",\n"
                + "        \"services\": \"network_services\",\n"
                + "        \"connectionLayer\": \"string\",\n"
                + "        \"serviceLayer\": \"string\",\n"
                + "        \"circuits\": \"string\",\n"
                + "        \"circuitsLayer\": \"string\",\n"
                + "        \"domainDescription\": \"string\",\n"
                + "        \"metrics\": \"string\",\n"
                + "        \"resourceCount\": 0,\n"
                + "        \"connectionCount\": 0,\n"
                + "        \"circuitCount\": 0,\n"
                + "        \"serviceCount\": 0,\n"
                + "        \"atomicId\": 0,\n"
                + "        \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "        \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "      },\n"
                + "      \"domainName\": \"string\",\n"
                + "      \"metricName\": \"string\",\n"
                + "      \"metricShort\": \"string\",\n"
                + "      \"metricDescription\": \"string\",\n"
                + "      \"metricValue\": 0,\n"
                + "      \"minValue\": 0,\n"
                + "      \"maxValue\": 0,\n"
                + "      \"unitValue\": 0,\n"
                + "      \"category\": \"string\"\n"
                + "    },\n"
                + "    \"consumerMetric\": {\n"
                + "      \"id\": \"string\",\n"
                + "      \"key\": \"string\",\n"
                + "      \"domain\": {\n"
                + "        \"domainName\": \"network\",\n"
                + "        \"connections\": \"network_connections\",\n"
                + "        \"nodes\": \"network_nodes\",\n"
                + "        \"serviceConnections\": \"string\",\n"
                + "        \"services\": \"network_services\",\n"
                + "        \"connectionLayer\": \"string\",\n"
                + "        \"serviceLayer\": \"string\",\n"
                + "        \"circuits\": \"string\",\n"
                + "        \"circuitsLayer\": \"string\",\n"
                + "        \"domainDescription\": \"string\",\n"
                + "        \"metrics\": \"string\",\n"
                + "        \"resourceCount\": 0,\n"
                + "        \"connectionCount\": 0,\n"
                + "        \"circuitCount\": 0,\n"
                + "        \"serviceCount\": 0,\n"
                + "        \"atomicId\": 0,\n"
                + "        \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "        \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "      },\n"
                + "      \"domainName\": \"string\",\n"
                + "      \"metricName\": \"string\",\n"
                + "      \"metricShort\": \"string\",\n"
                + "      \"metricDescription\": \"string\",\n"
                + "      \"metricValue\": 0,\n"
                + "      \"minValue\": 0,\n"
                + "      \"maxValue\": 0,\n"
                + "      \"unitValue\": 0,\n"
                + "      \"category\": \"string\"\n"
                + "    },\n"
                + "    \"name\": \"string\",\n"
                + "    \"description\": \"string\",\n"
                + "    \"nodeAddress\": \"string\",\n"
                + "    \"vendor\": \"string\",\n"
                + "    \"version\": \"string\",\n"
                + "    \"owner\": \"string\",\n"
                + "    \"author\": \"string\",\n"
                + "    \"resourceType\": \"string\",\n"
                + "    \"attributeSchemaName\": \"string\",\n"
                + "    \"category\": \"string\",\n"
                + "    \"adminStatus\": \"string\",\n"
                + "    \"operationalStatus\": \"string\",\n"
                + "    \"businessStatus\": \"string\",\n"
                + "    \"node\": \"string\",\n"
                + "    \"structureId\": \"string\",\n"
                + "    \"tags\": [\n"
                + "      \"string\"\n"
                + "    ],\n"
                + "    \"key\": \"string\",\n"
                + "    \"id\": \"string\",\n"
                + "    \"className\": \"string\",\n"
                + "    \"attributes\": {\n"
                + "      \"additionalProp1\": {},\n"
                + "      \"additionalProp2\": {},\n"
                + "      \"additionalProp3\": {}\n"
                + "    },\n"
                + "    \"discoveryAttributes\": {\n"
                + "      \"additionalProp1\": {},\n"
                + "      \"additionalProp2\": {},\n"
                + "      \"additionalProp3\": {}\n"
                + "    },\n"
                + "    \"atomId\": 0,\n"
                + "    \"schemaModel\": {\n"
                + "      \"schemaName\": \"string\",\n"
                + "      \"fromSchema\": \"string\",\n"
                + "      \"owner\": \"string\",\n"
                + "      \"author\": \"string\",\n"
                + "      \"allowAll\": true,\n"
                + "      \"attributesChanged\": true,\n"
                + "      \"isValid\": true,\n"
                + "      \"attributes\": {\n"
                + "        \"additionalProp1\": {\n"
                + "          \"name\": \"string\",\n"
                + "          \"variableType\": \"string\",\n"
                + "          \"description\": \"string\",\n"
                + "          \"defaultValue\": \"string\",\n"
                + "          \"allowedValues\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"required\": true,\n"
                + "          \"isList\": true,\n"
                + "          \"trackChanges\": true,\n"
                + "          \"minOccurrences\": 0,\n"
                + "          \"maxOccurrences\": 0,\n"
                + "          \"validationRegex\": \"string\",\n"
                + "          \"validationScript\": \"string\",\n"
                + "          \"validationPluginClass\": \"string\",\n"
                + "          \"validate\": true,\n"
                + "          \"itemHash\": \"string\",\n"
                + "          \"doRemove\": true,\n"
                + "          \"isDiscovery\": true,\n"
                + "          \"id\": \"string\"\n"
                + "        },\n"
                + "        \"additionalProp2\": {\n"
                + "          \"name\": \"string\",\n"
                + "          \"variableType\": \"string\",\n"
                + "          \"description\": \"string\",\n"
                + "          \"defaultValue\": \"string\",\n"
                + "          \"allowedValues\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"required\": true,\n"
                + "          \"isList\": true,\n"
                + "          \"trackChanges\": true,\n"
                + "          \"minOccurrences\": 0,\n"
                + "          \"maxOccurrences\": 0,\n"
                + "          \"validationRegex\": \"string\",\n"
                + "          \"validationScript\": \"string\",\n"
                + "          \"validationPluginClass\": \"string\",\n"
                + "          \"validate\": true,\n"
                + "          \"itemHash\": \"string\",\n"
                + "          \"doRemove\": true,\n"
                + "          \"isDiscovery\": true,\n"
                + "          \"id\": \"string\"\n"
                + "        },\n"
                + "        \"additionalProp3\": {\n"
                + "          \"name\": \"string\",\n"
                + "          \"variableType\": \"string\",\n"
                + "          \"description\": \"string\",\n"
                + "          \"defaultValue\": \"string\",\n"
                + "          \"allowedValues\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"required\": true,\n"
                + "          \"isList\": true,\n"
                + "          \"trackChanges\": true,\n"
                + "          \"minOccurrences\": 0,\n"
                + "          \"maxOccurrences\": 0,\n"
                + "          \"validationRegex\": \"string\",\n"
                + "          \"validationScript\": \"string\",\n"
                + "          \"validationPluginClass\": \"string\",\n"
                + "          \"validate\": true,\n"
                + "          \"itemHash\": \"string\",\n"
                + "          \"doRemove\": true,\n"
                + "          \"isDiscovery\": true,\n"
                + "          \"id\": \"string\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"childrenSchemas\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"relatedSchemas\": [\n"
                + "        \"string\"\n"
                + "      ]\n"
                + "    },\n"
                + "    \"revisionId\": \"string\",\n"
                + "    \"eventSourceIds\": [\n"
                + "      \"string\"\n"
                + "    ],\n"
                + "    \"dependentService\": {\n"
                + "      \"domain\": {\n"
                + "        \"domainName\": \"network\",\n"
                + "        \"connections\": \"network_connections\",\n"
                + "        \"nodes\": \"network_nodes\",\n"
                + "        \"serviceConnections\": \"string\",\n"
                + "        \"services\": \"network_services\",\n"
                + "        \"connectionLayer\": \"string\",\n"
                + "        \"serviceLayer\": \"string\",\n"
                + "        \"circuits\": \"string\",\n"
                + "        \"circuitsLayer\": \"string\",\n"
                + "        \"domainDescription\": \"string\",\n"
                + "        \"metrics\": \"string\",\n"
                + "        \"resourceCount\": 0,\n"
                + "        \"connectionCount\": 0,\n"
                + "        \"circuitCount\": 0,\n"
                + "        \"serviceCount\": 0,\n"
                + "        \"atomicId\": 0,\n"
                + "        \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "        \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "      },\n"
                + "      \"domainName\": \"network\",\n"
                + "      \"installationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "      \"activationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "      \"inactivationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "      \"lastModifiedDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "      \"insertedDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "      \"deleted\": true,\n"
                + "      \"readOnly\": true,\n"
                + "      \"isLeaf\": true,\n"
                + "      \"isConsumable\": true,\n"
                + "      \"isConsumer\": true,\n"
                + "      \"consumableMetric\": {\n"
                + "        \"id\": \"string\",\n"
                + "        \"key\": \"string\",\n"
                + "        \"domain\": {\n"
                + "          \"domainName\": \"network\",\n"
                + "          \"connections\": \"network_connections\",\n"
                + "          \"nodes\": \"network_nodes\",\n"
                + "          \"serviceConnections\": \"string\",\n"
                + "          \"services\": \"network_services\",\n"
                + "          \"connectionLayer\": \"string\",\n"
                + "          \"serviceLayer\": \"string\",\n"
                + "          \"circuits\": \"string\",\n"
                + "          \"circuitsLayer\": \"string\",\n"
                + "          \"domainDescription\": \"string\",\n"
                + "          \"metrics\": \"string\",\n"
                + "          \"resourceCount\": 0,\n"
                + "          \"connectionCount\": 0,\n"
                + "          \"circuitCount\": 0,\n"
                + "          \"serviceCount\": 0,\n"
                + "          \"atomicId\": 0,\n"
                + "          \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "          \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "        },\n"
                + "        \"domainName\": \"string\",\n"
                + "        \"metricName\": \"string\",\n"
                + "        \"metricShort\": \"string\",\n"
                + "        \"metricDescription\": \"string\",\n"
                + "        \"metricValue\": 0,\n"
                + "        \"minValue\": 0,\n"
                + "        \"maxValue\": 0,\n"
                + "        \"unitValue\": 0,\n"
                + "        \"category\": \"string\"\n"
                + "      },\n"
                + "      \"consumerMetric\": {\n"
                + "        \"id\": \"string\",\n"
                + "        \"key\": \"string\",\n"
                + "        \"domain\": {\n"
                + "          \"domainName\": \"network\",\n"
                + "          \"connections\": \"network_connections\",\n"
                + "          \"nodes\": \"network_nodes\",\n"
                + "          \"serviceConnections\": \"string\",\n"
                + "          \"services\": \"network_services\",\n"
                + "          \"connectionLayer\": \"string\",\n"
                + "          \"serviceLayer\": \"string\",\n"
                + "          \"circuits\": \"string\",\n"
                + "          \"circuitsLayer\": \"string\",\n"
                + "          \"domainDescription\": \"string\",\n"
                + "          \"metrics\": \"string\",\n"
                + "          \"resourceCount\": 0,\n"
                + "          \"connectionCount\": 0,\n"
                + "          \"circuitCount\": 0,\n"
                + "          \"serviceCount\": 0,\n"
                + "          \"atomicId\": 0,\n"
                + "          \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "          \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "        },\n"
                + "        \"domainName\": \"string\",\n"
                + "        \"metricName\": \"string\",\n"
                + "        \"metricShort\": \"string\",\n"
                + "        \"metricDescription\": \"string\",\n"
                + "        \"metricValue\": 0,\n"
                + "        \"minValue\": 0,\n"
                + "        \"maxValue\": 0,\n"
                + "        \"unitValue\": 0,\n"
                + "        \"category\": \"string\"\n"
                + "      },\n"
                + "      \"name\": \"string\",\n"
                + "      \"description\": \"string\",\n"
                + "      \"nodeAddress\": \"string\",\n"
                + "      \"vendor\": \"string\",\n"
                + "      \"version\": \"string\",\n"
                + "      \"owner\": \"string\",\n"
                + "      \"author\": \"string\",\n"
                + "      \"resourceType\": \"string\",\n"
                + "      \"attributeSchemaName\": \"string\",\n"
                + "      \"category\": \"string\",\n"
                + "      \"adminStatus\": \"string\",\n"
                + "      \"operationalStatus\": \"string\",\n"
                + "      \"businessStatus\": \"string\",\n"
                + "      \"node\": \"string\",\n"
                + "      \"structureId\": \"string\",\n"
                + "      \"tags\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"key\": \"string\",\n"
                + "      \"id\": \"string\",\n"
                + "      \"className\": \"string\",\n"
                + "      \"attributes\": {\n"
                + "        \"additionalProp1\": {},\n"
                + "        \"additionalProp2\": {},\n"
                + "        \"additionalProp3\": {}\n"
                + "      },\n"
                + "      \"discoveryAttributes\": {\n"
                + "        \"additionalProp1\": {},\n"
                + "        \"additionalProp2\": {},\n"
                + "        \"additionalProp3\": {}\n"
                + "      },\n"
                + "      \"atomId\": 0,\n"
                + "      \"schemaModel\": {\n"
                + "        \"schemaName\": \"string\",\n"
                + "        \"fromSchema\": \"string\",\n"
                + "        \"owner\": \"string\",\n"
                + "        \"author\": \"string\",\n"
                + "        \"allowAll\": true,\n"
                + "        \"attributesChanged\": true,\n"
                + "        \"isValid\": true,\n"
                + "        \"attributes\": {\n"
                + "          \"additionalProp1\": {\n"
                + "            \"name\": \"string\",\n"
                + "            \"variableType\": \"string\",\n"
                + "            \"description\": \"string\",\n"
                + "            \"defaultValue\": \"string\",\n"
                + "            \"allowedValues\": [\n"
                + "              \"string\"\n"
                + "            ],\n"
                + "            \"required\": true,\n"
                + "            \"isList\": true,\n"
                + "            \"trackChanges\": true,\n"
                + "            \"minOccurrences\": 0,\n"
                + "            \"maxOccurrences\": 0,\n"
                + "            \"validationRegex\": \"string\",\n"
                + "            \"validationScript\": \"string\",\n"
                + "            \"validationPluginClass\": \"string\",\n"
                + "            \"validate\": true,\n"
                + "            \"itemHash\": \"string\",\n"
                + "            \"doRemove\": true,\n"
                + "            \"isDiscovery\": true,\n"
                + "            \"id\": \"string\"\n"
                + "          },\n"
                + "          \"additionalProp2\": {\n"
                + "            \"name\": \"string\",\n"
                + "            \"variableType\": \"string\",\n"
                + "            \"description\": \"string\",\n"
                + "            \"defaultValue\": \"string\",\n"
                + "            \"allowedValues\": [\n"
                + "              \"string\"\n"
                + "            ],\n"
                + "            \"required\": true,\n"
                + "            \"isList\": true,\n"
                + "            \"trackChanges\": true,\n"
                + "            \"minOccurrences\": 0,\n"
                + "            \"maxOccurrences\": 0,\n"
                + "            \"validationRegex\": \"string\",\n"
                + "            \"validationScript\": \"string\",\n"
                + "            \"validationPluginClass\": \"string\",\n"
                + "            \"validate\": true,\n"
                + "            \"itemHash\": \"string\",\n"
                + "            \"doRemove\": true,\n"
                + "            \"isDiscovery\": true,\n"
                + "            \"id\": \"string\"\n"
                + "          },\n"
                + "          \"additionalProp3\": {\n"
                + "            \"name\": \"string\",\n"
                + "            \"variableType\": \"string\",\n"
                + "            \"description\": \"string\",\n"
                + "            \"defaultValue\": \"string\",\n"
                + "            \"allowedValues\": [\n"
                + "              \"string\"\n"
                + "            ],\n"
                + "            \"required\": true,\n"
                + "            \"isList\": true,\n"
                + "            \"trackChanges\": true,\n"
                + "            \"minOccurrences\": 0,\n"
                + "            \"maxOccurrences\": 0,\n"
                + "            \"validationRegex\": \"string\",\n"
                + "            \"validationScript\": \"string\",\n"
                + "            \"validationPluginClass\": \"string\",\n"
                + "            \"validate\": true,\n"
                + "            \"itemHash\": \"string\",\n"
                + "            \"doRemove\": true,\n"
                + "            \"isDiscovery\": true,\n"
                + "            \"id\": \"string\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"childrenSchemas\": [\n"
                + "          \"string\"\n"
                + "        ],\n"
                + "        \"relatedSchemas\": [\n"
                + "          \"string\"\n"
                + "        ]\n"
                + "      },\n"
                + "      \"revisionId\": \"string\",\n"
                + "      \"eventSourceIds\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"dependencies\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"circuits\": [\n"
                + "        {\n"
                + "          \"domain\": {\n"
                + "            \"domainName\": \"network\",\n"
                + "            \"connections\": \"network_connections\",\n"
                + "            \"nodes\": \"network_nodes\",\n"
                + "            \"serviceConnections\": \"string\",\n"
                + "            \"services\": \"network_services\",\n"
                + "            \"connectionLayer\": \"string\",\n"
                + "            \"serviceLayer\": \"string\",\n"
                + "            \"circuits\": \"string\",\n"
                + "            \"circuitsLayer\": \"string\",\n"
                + "            \"domainDescription\": \"string\",\n"
                + "            \"metrics\": \"string\",\n"
                + "            \"resourceCount\": 0,\n"
                + "            \"connectionCount\": 0,\n"
                + "            \"circuitCount\": 0,\n"
                + "            \"serviceCount\": 0,\n"
                + "            \"atomicId\": 0,\n"
                + "            \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "            \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "          },\n"
                + "          \"domainName\": \"network\",\n"
                + "          \"installationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "          \"activationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "          \"inactivationDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "          \"lastModifiedDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "          \"insertedDate\": \"2023-07-01T16:15:32.248Z\",\n"
                + "          \"deleted\": true,\n"
                + "          \"readOnly\": true,\n"
                + "          \"isLeaf\": true,\n"
                + "          \"isConsumable\": true,\n"
                + "          \"isConsumer\": true,\n"
                + "          \"consumableMetric\": {\n"
                + "            \"id\": \"string\",\n"
                + "            \"key\": \"string\",\n"
                + "            \"domain\": {\n"
                + "              \"domainName\": \"network\",\n"
                + "              \"connections\": \"network_connections\",\n"
                + "              \"nodes\": \"network_nodes\",\n"
                + "              \"serviceConnections\": \"string\",\n"
                + "              \"services\": \"network_services\",\n"
                + "              \"connectionLayer\": \"string\",\n"
                + "              \"serviceLayer\": \"string\",\n"
                + "              \"circuits\": \"string\",\n"
                + "              \"circuitsLayer\": \"string\",\n"
                + "              \"domainDescription\": \"string\",\n"
                + "              \"metrics\": \"string\",\n"
                + "              \"resourceCount\": 0,\n"
                + "              \"connectionCount\": 0,\n"
                + "              \"circuitCount\": 0,\n"
                + "              \"serviceCount\": 0,\n"
                + "              \"atomicId\": 0,\n"
                + "              \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "              \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "            },\n"
                + "            \"domainName\": \"string\",\n"
                + "            \"metricName\": \"string\",\n"
                + "            \"metricShort\": \"string\",\n"
                + "            \"metricDescription\": \"string\",\n"
                + "            \"metricValue\": 0,\n"
                + "            \"minValue\": 0,\n"
                + "            \"maxValue\": 0,\n"
                + "            \"unitValue\": 0,\n"
                + "            \"category\": \"string\"\n"
                + "          },\n"
                + "          \"consumerMetric\": {\n"
                + "            \"id\": \"string\",\n"
                + "            \"key\": \"string\",\n"
                + "            \"domain\": {\n"
                + "              \"domainName\": \"network\",\n"
                + "              \"connections\": \"network_connections\",\n"
                + "              \"nodes\": \"network_nodes\",\n"
                + "              \"serviceConnections\": \"string\",\n"
                + "              \"services\": \"network_services\",\n"
                + "              \"connectionLayer\": \"string\",\n"
                + "              \"serviceLayer\": \"string\",\n"
                + "              \"circuits\": \"string\",\n"
                + "              \"circuitsLayer\": \"string\",\n"
                + "              \"domainDescription\": \"string\",\n"
                + "              \"metrics\": \"string\",\n"
                + "              \"resourceCount\": 0,\n"
                + "              \"connectionCount\": 0,\n"
                + "              \"circuitCount\": 0,\n"
                + "              \"serviceCount\": 0,\n"
                + "              \"atomicId\": 0,\n"
                + "              \"lastStatsCalc\": \"2023-04-18T23:20:00Z\",\n"
                + "              \"lastUpdate\": \"2023-04-18T23:20:00Z\"\n"
                + "            },\n"
                + "            \"domainName\": \"string\",\n"
                + "            \"metricName\": \"string\",\n"
                + "            \"metricShort\": \"string\",\n"
                + "            \"metricDescription\": \"string\",\n"
                + "            \"metricValue\": 0,\n"
                + "            \"minValue\": 0,\n"
                + "            \"maxValue\": 0,\n"
                + "            \"unitValue\": 0,\n"
                + "            \"category\": \"string\"\n"
                + "          },\n"
                + "          \"name\": \"string\",\n"
                + "          \"description\": \"string\",\n"
                + "          \"nodeAddress\": \"string\",\n"
                + "          \"vendor\": \"string\",\n"
                + "          \"version\": \"string\",\n"
                + "          \"owner\": \"string\",\n"
                + "          \"author\": \"string\",\n"
                + "          \"resourceType\": \"string\",\n"
                + "          \"attributeSchemaName\": \"string\",\n"
                + "          \"category\": \"string\",\n"
                + "          \"adminStatus\": \"string\",\n"
                + "          \"operationalStatus\": \"string\",\n"
                + "          \"businessStatus\": \"string\",\n"
                + "          \"node\": \"string\",\n"
                + "          \"structureId\": \"string\",\n"
                + "          \"tags\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"key\": \"string\",\n"
                + "          \"id\": \"string\",\n"
                + "          \"className\": \"string\",\n"
                + "          \"attributes\": {\n"
                + "            \"additionalProp1\": {},\n"
                + "            \"additionalProp2\": {},\n"
                + "            \"additionalProp3\": {}\n"
                + "          },\n"
                + "          \"discoveryAttributes\": {\n"
                + "            \"additionalProp1\": {},\n"
                + "            \"additionalProp2\": {},\n"
                + "            \"additionalProp3\": {}\n"
                + "          },\n"
                + "          \"atomId\": 0,\n"
                + "          \"schemaModel\": {\n"
                + "            \"schemaName\": \"string\",\n"
                + "            \"fromSchema\": \"string\",\n"
                + "            \"owner\": \"string\",\n"
                + "            \"author\": \"string\",\n"
                + "            \"allowAll\": true,\n"
                + "            \"attributesChanged\": true,\n"
                + "            \"isValid\": true,\n"
                + "            \"attributes\": {\n"
                + "              \"additionalProp1\": {\n"
                + "                \"name\": \"string\",\n"
                + "                \"variableType\": \"string\",\n"
                + "                \"description\": \"string\",\n"
                + "                \"defaultValue\": \"string\",\n"
                + "                \"allowedValues\": [\n"
                + "                  \"string\"\n"
                + "                ],\n"
                + "                \"required\": true,\n"
                + "                \"isList\": true,\n"
                + "                \"trackChanges\": true,\n"
                + "                \"minOccurrences\": 0,\n"
                + "                \"maxOccurrences\": 0,\n"
                + "                \"validationRegex\": \"string\",\n"
                + "                \"validationScript\": \"string\",\n"
                + "                \"validationPluginClass\": \"string\",\n"
                + "                \"validate\": true,\n"
                + "                \"itemHash\": \"string\",\n"
                + "                \"doRemove\": true,\n"
                + "                \"isDiscovery\": true,\n"
                + "                \"id\": \"string\"\n"
                + "              },\n"
                + "              \"additionalProp2\": {\n"
                + "                \"name\": \"string\",\n"
                + "                \"variableType\": \"string\",\n"
                + "                \"description\": \"string\",\n"
                + "                \"defaultValue\": \"string\",\n"
                + "                \"allowedValues\": [\n"
                + "                  \"string\"\n"
                + "                ],\n"
                + "                \"required\": true,\n"
                + "                \"isList\": true,\n"
                + "                \"trackChanges\": true,\n"
                + "                \"minOccurrences\": 0,\n"
                + "                \"maxOccurrences\": 0,\n"
                + "                \"validationRegex\": \"string\",\n"
                + "                \"validationScript\": \"string\",\n"
                + "                \"validationPluginClass\": \"string\",\n"
                + "                \"validate\": true,\n"
                + "                \"itemHash\": \"string\",\n"
                + "                \"doRemove\": true,\n"
                + "                \"isDiscovery\": true,\n"
                + "                \"id\": \"string\"\n"
                + "              },\n"
                + "              \"additionalProp3\": {\n"
                + "                \"name\": \"string\",\n"
                + "                \"variableType\": \"string\",\n"
                + "                \"description\": \"string\",\n"
                + "                \"defaultValue\": \"string\",\n"
                + "                \"allowedValues\": [\n"
                + "                  \"string\"\n"
                + "                ],\n"
                + "                \"required\": true,\n"
                + "                \"isList\": true,\n"
                + "                \"trackChanges\": true,\n"
                + "                \"minOccurrences\": 0,\n"
                + "                \"maxOccurrences\": 0,\n"
                + "                \"validationRegex\": \"string\",\n"
                + "                \"validationScript\": \"string\",\n"
                + "                \"validationPluginClass\": \"string\",\n"
                + "                \"validate\": true,\n"
                + "                \"itemHash\": \"string\",\n"
                + "                \"doRemove\": true,\n"
                + "                \"isDiscovery\": true,\n"
                + "                \"id\": \"string\"\n"
                + "              }\n"
                + "            },\n"
                + "            \"childrenSchemas\": [\n"
                + "              \"string\"\n"
                + "            ],\n"
                + "            \"relatedSchemas\": [\n"
                + "              \"string\"\n"
                + "            ]\n"
                + "          },\n"
                + "          \"revisionId\": \"string\",\n"
                + "          \"eventSourceIds\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"degrated\": true,\n"
                + "          \"broken\": true,\n"
                + "          \"brokenResources\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"getaPoint\": \"string\",\n"
                + "          \"getzPoint\": \"string\",\n"
                + "          \"services\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"circuitPath\": [\n"
                + "            \"string\"\n"
                + "          ],\n"
                + "          \"objectClass\": \"string\"\n"
                + "        }\n"
                + "      ],\n"
                + "      \"relatedServices\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"relatedManagedResources\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"relatedResourceConnections\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"degrated\": true,\n"
                + "      \"broken\": true,\n"
                + "      \"brokenResources\": [\n"
                + "        \"string\"\n"
                + "      ],\n"
                + "      \"objectClass\": \"string\"\n"
                + "    },\n"
                + "    \"objectClass\": \"string\"\n"
                + "  },\n"
                + "  \"size\": 0,\n"
                + "  \"className\": \"string\",\n"
                + "  \"arangoStats\": {\n"
                + "    \"writesExecuted\": 0,\n"
                + "    \"writesIgnored\": 0,\n"
                + "    \"scannedFull\": 0,\n"
                + "    \"scannedIndex\": 0,\n"
                + "    \"filtered\": 0,\n"
                + "    \"fullCount\": 0,\n"
                + "    \"executionTime\": 0,\n"
                + "    \"peakMemoryUsage\": 0,\n"
                + "    \"cursorsCreated\": 0,\n"
                + "    \"cursorsRearmed\": 0,\n"
                + "    \"cacheHits\": 0,\n"
                + "    \"cacheMisses\": 0\n"
                + "  }\n"
                + "}";

        String json2 = "[\n"
                + "   {\n"
                + "      \"_id\":\"dwdm_nodes/21c51eed-dc7c-430a-bce0-81cad079ea1d\",\n"
                + "      \"_key\":\"21c51eed-dc7c-430a-bce0-81cad079ea1d\",\n"
                + "      \"_rev\":\"_gR80I7y---\",\n"
                + "      \"adminStatus\":\"Up\",\n"
                + "      \"atomId\":3207,\n"
                + "      \"attachments\":{\n"
                + "         \n"
                + "      },\n"
                + "      \"attributeSchemaName\":\"resource.dwdm\",\n"
                + "      \"attributes\":{\n"
                + "         \"id_equip\":9214,\n"
                + "         \"vendor\":\"Ciena\",\n"
                + "         \"siglaSite\":\"PNRMS\",\n"
                + "         \"enderecoIP\":\"10.113.133.22/27\",\n"
                + "         \"enderecoIP2\":\"10.164.118.151/27\",\n"
                + "         \"funcaoEnderecoIP\":\"Gerência\",\n"
                + "         \"funcaoEnderecoIP2\":\"Gerência\",\n"
                + "         \"origem\":\"smtx\"\n"
                + "      }\n"
                + "   }\n"
                + "]";
        List<String> fields = Arrays.asList("$root.payLoad.attributes.*");
        String filteredJson = JsonFilterTest.filterJson(yourJsonString, fields);
        System.out.println(filteredJson);
    }

    public static String filterJson(String json, List<String> fields) {
        Set<String> fieldSet = new HashSet<>(fields);
        ObjectMapper objectMapper = new ObjectMapper();

        try {
            JsonNode jsonNode = objectMapper.readTree(json);
            JsonNode result;

            if (jsonNode.isArray()) {
                ArrayNode arrayNode = objectMapper.createArrayNode();
                for (int i = 0; i < jsonNode.size(); i++) {
                    JsonNode child = filter(jsonNode.get(i), fieldSet, "$root.[*]", objectMapper);
                    if (child != null && !child.isEmpty(objectMapper.getSerializerProvider())) {
                        arrayNode.add(child);
                    }
                }
                result = arrayNode;
            } else {
                result = filter(jsonNode, fieldSet, "$root", objectMapper);
            }

            return result != null ? result.toString() : null;
        } catch (IOException e) {
            throw new RuntimeException("Falha ao processar o JSON", e);
        }
    }

    private static JsonNode filter(JsonNode jsonNode, Set<String> fields, String currentPath, ObjectMapper objectMapper) {
        if (jsonNode.isObject()) {
            ObjectNode objectNode = objectMapper.createObjectNode();
            jsonNode.fields().forEachRemaining(field -> {
                String updatedPath = currentPath + "." + field.getKey();
                if (fields.contains(updatedPath) || anyStartsWith(fields, updatedPath) || isWildcardMatch(fields, currentPath)) {
                    JsonNode child = filter(field.getValue(), fields, updatedPath, objectMapper);
                    if (child != null) {
                        objectNode.set(field.getKey(), child);
                    }
                }
            });
            return objectNode;
        } else if (jsonNode.isArray()) {
            ArrayNode arrayNode = objectMapper.createArrayNode();
            jsonNode.elements().forEachRemaining(element -> {
                JsonNode child = filter(element, fields, currentPath + ".[*]", objectMapper);
                if (child != null && !child.isEmpty(objectMapper.getSerializerProvider())) {
                    arrayNode.add(child);
                }
            });
            return arrayNode;
        } else {
            return jsonNode.deepCopy();
        }
    }

    private static boolean anyStartsWith(Set<String> fields, String path) {
        return fields.stream().anyMatch(field -> field.startsWith(path + "."));
    }

    private static boolean isWildcardMatch(Set<String> fields, String path) {
        return fields.contains(path + ".*") || fields.contains(path + ".[*].*");
    }

}
