apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcompass-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netcompass-api-deployment
  template:
    metadata:
      labels:
        app: netcompass-api-deployment
    spec:
      containers:
      - name: inventory-manager-api
        metadata:
          labels:
            app: netcompass-api
        image: quay.apps.mgmt.telcostack.br.telefonica.com/netcompass/netcompass-server/netcompass-api
        resources:
          requests:
            memory: "24576Mi"
            cpu: "8"
          limits:
            memory: "24576Mi"
            cpu: "16"
        ports:
          - name: api-https
            containerPort: 9000
            protocol: TCP
        volumeMounts:
          - name: netcompass-app-volume
            mountPath: /app/inventory-manager/schema
          - name: config-volume
            mountPath: /app/inventory-manager/config/
        env:
          - name: JAR_PATH
            value: /app/inventory-manager
          - name: JAR_ARGS
            value: -Xmx16G -Dspring.profiles.active=mvp
          - name: JAR_NAME
            value: inventory-manager-1.0.0-alpha.jar
          - name: SPRING_PROFILES_DEFAULT
            value: prod
      volumes:
        - name: netcompass-app-volume
          persistentVolumeClaim:
            claimName: netcompass-app-volume-claim
        - name: config-volume
          configMap:
            name: inventory-config
