apiVersion: v1
kind: PersistentVolume
metadata:
  name: netcompass-app-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /app/inventory-manager
