apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netcompass-app-volume-claim
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi